// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmAKYhn9Ztg7K_KTiST0RvQZi2BzSVkFY',
    appId: '1:336436096165:web:7032b8bff0d20810f7714c',
    messagingSenderId: '336436096165',
    projectId: 'school-ced38',
    authDomain: 'school-ced38.firebaseapp.com',
    databaseURL: 'https://school-ced38-default-rtdb.firebaseio.com',
    storageBucket: 'school-ced38.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9nL1QqZzJd4KsmAi-HA1HDH0T2EyzfFI',
    appId: '1:336436096165:android:f6ee4c92fb96b658f7714c',
    messagingSenderId: '336436096165',
    projectId: 'school-ced38',
    databaseURL: 'https://school-ced38-default-rtdb.firebaseio.com',
    storageBucket: 'school-ced38.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF_UMOosXF_CDAzQqUCbpq7ozCVMOFVjU',
    appId: '1:336436096165:ios:c9e4ed94618c9151f7714c',
    messagingSenderId: '336436096165',
    projectId: 'school-ced38',
    databaseURL: 'https://school-ced38-default-rtdb.firebaseio.com',
    storageBucket: 'school-ced38.appspot.com',
    iosClientId: '336436096165-r9u9dtl480l23p4rt4rcco4fj18mmoos.apps.googleusercontent.com',
    iosBundleId: 'com.example.okulum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF_UMOosXF_CDAzQqUCbpq7ozCVMOFVjU',
    appId: '1:336436096165:ios:c9e4ed94618c9151f7714c',
    messagingSenderId: '336436096165',
    projectId: 'school-ced38',
    databaseURL: 'https://school-ced38-default-rtdb.firebaseio.com',
    storageBucket: 'school-ced38.appspot.com',
    iosClientId: '336436096165-r9u9dtl480l23p4rt4rcco4fj18mmoos.apps.googleusercontent.com',
    iosBundleId: 'com.example.okulum',
  );
}
